### PR TITLE
Fix test dependency on test executable

### PR DESCRIPTION
**Pull request by qrilka**
This fixes tests for `cabal build`, `cabal new-build` and Stack.

### CODE REVIEW

**Comment by BartMassey** [comment]
Thanks much for this! Merged. I'm not a Stack person, so I especially appreciate the help there.

I'm not sure why the Travis build fails, but I'm not sure why it's running either, since I can't remember ever setting it up :smile:.

Any interest in co-maintaining `parseargs`? I don't use Haskell so much anymore, so having somebody who was on top of the current meta would be nice. I hadn't realized so much changed with `cabal`.

**Comment by qrilka** [comment]
I've stumbled upon this error while running Stackage tests and I'm not familiar with you package, I guess it would be better to ask some of its current users about co-maintainership.

**Comment by BartMassey** [comment]
Oh well. Not sure I even have many current users :smile:. Thanks again for the fix!

**Comment by qrilka** [comment]
@BartMassey do you have any plans to release this as a new minor version? Otherwise we'll be forced to put `parseargs` into `expected-test-failures` category

**Comment by BartMassey** [comment]
Done. Thanks for the note.

**Pull request merged**
